global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'ai-agent'
    static_configs:
      - targets: ['ai-agent:8501']

  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8080']

  - job_name: 'minio'
    static_configs:
      - targets: ['datalake:9000']