apisix:
  node_listen: 9080
  enable_ipv6: false

  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

routes:
  - uri: /api/*
    upstream:
      type: roundrobin
      nodes:
        "backend:8000": 1
    strip_uri: true

  - uri: /*
    upstream:
      type: roundrobin
      nodes:
        "frontend:8501": 1